server:
  port: 9008
spring:
  application:
    name: hrm-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_user
    username: root
    password: 147258
mybatis-plus:
  mapper-locations: classpath:com/zhang/hrm/mapper/*Mapper.xml
  type-aliases-package: com.zhang.hrm.domain,com.zhang.hrm.query